### ISSUE TITLE
VK2D_NAME change depending on Release/Debug build

### ISSUE THREAD

**Issue by exuvo** [Noxagonal/Vulkan2DRenderer#140]
As expected the Release/Debug VK2D_NAME change is a bit awkward for me to handle when VK2D is a dependency.

If i understand the reasoning correctly this is for the install part to spit out both release and debug dlls?
Could you elaborate why the install commands RENAME parameter does not work here?

How about adding an option for this that defaults off for pure cmake builds and you can set it to on in the python build script?
`
option(VK2D_SEPARATE_DEBUG_NAME "Change target name to VK2D_d when doing a debug build" OFF)
if(VK2D_SEPARATE_DEBUG_NAME AND CMAKE_BUILD_TYPE STREQUAL "Debug")
`

**Comment by Noxagonal** [comment]
I can add an option flag for this for sure. I'll add it to my todo for today.

Short answer is that "RENAME" install target didn't work for VS build.

In detail, VS builds require debug version of the library dll because (as I understood it) some stl/windows runtime types contain extra debug info that needs to pass between the library and the application, so I'm providing both Release and Debug dll. Switching between release and debug also requires the user of the library to swap out their dll files manually, so to make it more convenient it's better to provide each dll with a different name. VS also produces 2 files for dynamic libraries, the dll itself and a .lib that provides static linking to said dll. The lib contains the name of the dll so renaming both dll and lib to VK2D_d will still try and search for the VK2D.dll. The easiest way I could change the name was to change the name if the entire project.

**Comment by Noxagonal** [comment]
Unix makefiles is a single config while VS is multiple config system, causing some confusion and lack of foresight in this.
So I implemented these changes as suggested.
