### ISSUE TITLE
Way to query and append custom device and instance extensions

### ISSUE THREAD

**Issue by exuvo** [Noxagonal/Vulkan2DRenderer#156]
I have need of using VK_EXT_display_control and VK_EXT_display_surface_counter on linux to reduce latency by delaying polling and rendering to shortly before next vsync.

I was thinking of extending InstanceCreateInfo with another callback that receives two lists of available device and instance extensions and can then return the desired extensions and the user can set a bool somewhere to true if their desired extension was available.

Does that seem like an acceptable approach or would you prefer another way?

This extension seems to only work on linux and then only on 50% of devices (i think all new drivers support it) https://vulkan.gpuinfo.org/listextensions.php?platform=linux.

Ex normal way is: block for vsync 15ms, vsync, render, repeat.
You can instead do (simplified): vsync, sleep 12ms, render, block for vsync 3ms, repeat.
You can also skip the block for vsync and adjust the sleep time every frame to keep in sync with just before device refresh.

Sleep time should be time `vsync time (16ms) - rendering time (ex 5ms) - saftey margin for variable rendering time (3ms)`
In my case i sleep for 1ms less than desired and busy loop or yield the rest to ensure consistent sleep times.

**Comment by exuvo** [comment]
I did the above mentioned approach and it works with VK_EXT_display_control and VK_EXT_display_surface_counter https://github.com/exuvo/Vulkan2DRenderer/commit/37430a7844a72fc39885d299b9262973976ada4d.

Unfortunately i must be missing something in the documentation as i can call the API but all it tells me is that there is no vsync counter.

**Comment by Noxagonal** [comment]
I've been thinking about how to expose more features to the user application for a while now but I haven't really come to any solid consensus about it. Feel free to add your thoughts here too.
Here are my thoughts so far:
- Vulkan should be completely hidden from the interface so that people using pre-compiled `.dll` or `.so` don't have any additional dependencies via this library. This limits vulkan stuff to inside the library only, getting hardware supported features might need to be moderated, though I'm not completely against the idea of just getting them all for logging purposes, this would include extensions.
- Using a feature that might or might not be supported by the hardware should be set via the `vk2d::InstanceCreateInfo`, however since vulkan is hidden from the user application this list must be moderated, so if VK2D does not implement a feature it must not be made available to activate for the library (so basically a bool per feature, no text string activation), if a feature is implemented in library and activated by user program but not supported by the hardware then a warning should be reported and feature disabled and use of it ignored.
- If a feature is not implemented in library and user don't mind adding Vulkan SDK as dependency for their project, then some sort of extension system could be implemented if `VULKAN_H_` was defined... Or just tell users to fork it.
- Currently all used extensions are mandatory for this library so I'm just relying on instance or device creation to fail and bail out if something isn't supported. I'd eventually like to refine this a bit more to check for mandatory extensions and optional extensions.
- If an extension doesn't have any drawbacks, should it be always enabled on supported hardware? If it does have some drawbacks then it should of course only be enabled by request.
- Create info structures should be input only, debug message callback is an exception I want to get rid of. (Needs an extra mutex, just haven't got to it yet.)
- I'd like to enumerate supported instance and device extensions in a free function, or in a `vk2d::SystemInfo` class of some sort. For `vkEnumerateDeviceExtensionProperties()` a temporary vulkan instance could be created with default GPU, on Windows this takes around 30ms and 13Mb of RAM (i7-8700k). So doing this once a twice at the start shouldn't be a problem. If you have time I'd like to know how long `vkCreateInstance` takes on your system.
- I wanted to enable selecting the GPU as well which also requires creating a vulkan instance. So I'm considering a `vk2d::SystemInfo` class for this as well.
- I may just end up separating `vk2d::Instance` into `vk2d::Instance` and `vk2d::Device` but I'd prefer keeping everything in one package as much as possible. Easier for new users to pick up, faster for me to prototype simple stuff.

**Comment by exuvo** [comment]
I don't think hiding vulkan completly is a feasible goal. As soon as the user wants to implement a custom shader effect, which is quite common to want, you are back to needing vulkan headers during compilation.

Even if the user is not well versed in vulkan shaders themselves many effects can be readily found on the internet and users only really need access to the normal vulkan device, command buffer, etc, and a restore VK2D render pipeline function (or automated if you can register the custom shader in VK2D) to use them.

In my case i'm already using ImGui with VK2D which requires loading 1 shader and 1 texture. To restore the rendering state afterwards (was only needed if i wanted to draw with VK2D after drawing with imgui, otherwise begin frame would restore it all) i use the following:
```
// Will trigger rebinds
window.window->impl->previous_pipeline_settings = vk2d::_internal::GraphicsPipelineSettings {};
window.window->impl->mesh_buffer->bound_index_buffer_block = nullptr;
window.window->impl->mesh_buffer->bound_vertex_buffer_block = nullptr;

VkRect2D scissor {
	{ 0, 0 },
	window.window->impl->extent
};
vkCmdSetScissor(
	command_buffer,
	0, 1, &scissor
);

// Rebind-Window frame data.
vkCmdBindDescriptorSets(
	command_buffer,
	VK_PIPELINE_BIND_POINT_GRAPHICS,
	Aurora.vk2dInstance->impl->GetGraphicsPrimaryRenderPipelineLayout(),
	vk2d::_internal::GRAPHICS_DESCRIPTOR_SET_ALLOCATION_WINDOW_FRAME_DATA,
	1, &window.window->impl->frame_data_descriptor_set.descriptorSet,
	0, nullptr
);
```

All the name definitions for vulkan extensions are in the vulkan headers, forcing users to manually type the extension names seems like it could introduce unnecessary bugs and waste programmer time debugging.

Maybe it would be possible to have two include directories, one for simple usage, and another that exposes more advanced functions? Not entirely sure if that would work. As an example think of having the impl headers in the advanced include directory where lower level vulkan stuff is exposed. Then you would only need vulkan headers for compilation if you include a header from the advanced directory.

Regarding a temporary vulkan instance for SystemInfo and vkEnumerateDeviceExtensionProperties it would have to use the same GPU selection logic as the main code as it would not be useful to get extensions for a different GPU than what will be used. Personally i don't like unnecessary time wasting even if its only 30ms (stuff adds up over time), when it can be avoided with a callback. With the above mentioned advanced include directory you could have a second CreateInstance function in there which takes an extra InstanceCreateInfoAdvanced struct that has all the callbacks and other uncommon settings.

For custom GPU selection i think the normal use case is that you first start with whatever GPU and then the user can change it it in the games settings if it was wrong, then a game restart is usually expected (or automatic recreation of the vulkan instance but most games ive done this in force a restart). What i mean is that i don't think you need to have a API to enumerate the GPUs before creating the normal instance as the programmer at this point don't know the users preference yet.

**Comment by Noxagonal** [comment]
Interesting idea to scale the library between simple and advanced sets, I think that should be doable with some organizing of the files. I'll look into it more, right now I'm not a huge fan of this idea as I believe in simplicity first, if it becomes too constricted then I can expand as needed.
I'm not saying that you shouldn't modify internal data structures yourself but vk2d is not really meant for that. It will likely introduce some bugs later at some point and I'm trying to keep somewhat of a safety net going for new users, so if more advanced features are exposed then I'd have to make sure they're properly curated as well.

I'm curious what features exactly you find lacking or missing. From what I can collect it's vulkan extensions and custom shaders.

For the shaders I could include glslang inside the library. This would allow compiling and using glsl directly. The reasons why I made the external compiler tool is that I could reuse shader interfaces easier, build the shader code into the library and prevent unnecessary recompiling during runtime.

So I could allow building glsl in the library with slow compilation speed (especially on debug), allow loading spir-v shaders, create external tool to pre-compile shaders. I'm kinda leaning towards all 3.

Most of the default shader interface wouldn't make sense in this context so shader interface would be hidden and the user would only need to write the entrypoint function, this user shader code could be appended to build-in glsl string which would offer the interface and helper functions to the user shader code. For example instead of calling `texture( sampler2DArray( sampled_image, image_sampler ), vec3( fragment_input_UV, float( i ) ) );` user could use simple `Texture( uv, layer );`

Getting custom data to user shaders shouldn't be too much of a problem either.

GPU selection could be forced via `vk2d::InstanceCreateInfo`, normally vk2d will try and find the best one but if that fails. I'd still like a way query for all GPUs ahead of creating fully creating the instance. Don't know about this yet...

**Comment by exuvo** [comment]
At this point it's only the custom shaders that i need. My testing with the above extensions has proven fruitless on my system so i'll drop that for now.

Loading spir-v would be enough for me as i can just call external a spir-v compiler or link in glslang myself.

I would prefer if the shaders don't have to be written in a specific way just for VK2D as that limits portability with examples found on the internet. I have no idea how you are going to pass data to a custom shader without allowing the user to set up the VertexInputAttributeDescriptions and pipeline. Unless you meant to restrict the shaders to the same format the current vk2d mesh uses.

As an example an strategic icon shader i have yet to port from my old openGL project needs one bound texture, two texture coordinates, a color and a vec2 position. I expect that to be around a third of the things on the screen so a minimal vertex format is desired.

If you can make a non vulkan interface that is flexible enough then fine, but i'll probably just stick to raw vulkan with minor visibility changes in my fork of VK2D and semi-manual restoring of render state where needed.

**Comment by Noxagonal** [comment]
I've decided that I want VK2D to be primarily high level library so I'll focus on implementing managed features first before directly exposing any of the lower level functionality.

I've also decided to implement custom shaders, shader interfaces and ability to pass user data to shader, although it will require quite some refactoring and generalizing the code.
https://github.com/Noxagonal/Vulkan2DRenderer/issues/164
https://github.com/Noxagonal/Vulkan2DRenderer/discussions/163

I'm closing issue for now.
