### ISSUE TITLE
Possible bug in DescriptorSet.c

### ISSUE THREAD

**Issue by exuvo** [Noxagonal/Vulkan2DRenderer#167]
line 228 in DescriptorSet.c:
```
case VK_ERROR_OUT_OF_POOL_MEMORY:		// 1.1 ( After VK_KHR_maintenance1 )
//case VK_ERROR_OUT_OF_DEVICE_MEMORY:		// 1.0 ( Before VK_KHR_maintenance1 )
// Mark as full, try next pool
sc.second->isFull	= true;
break;
```
The comment implies it should be a continue instead of a break there.

**Comment by exuvo** [comment]
Also what is the point of the `++it` on line 340 when it breaks right after?

**Comment by Noxagonal** [comment]
Heh. It's been a while since I had time to look at this code.

"continue" should work just fine, I just don't prefer it. "continue" isn't quite explicit enough for me and I keep missing it when reading the code, and then I get confused later. Could be just me though. Anyways I prefer to structure my code so that I don't have to use it. This won't change anything in this case.

The iterator increment on line 340 is not needed, this slipped by me.

**Comment by exuvo** [comment]
Ah sorry i was thinking the break was for the surrounding for loop but of course it is for the case. Code is good then.
